# The pinned autoparser repeats per-call JSON wrappers even when parallel calls
# are disabled. Compile a corrected copy; never modify an external checkout.
function(iilocal_fix_llama_tool_call_limit)
    get_target_property(_common_dir llama-common SOURCE_DIR)
    set(_generator "${_common_dir}/chat-auto-parser-generator.cpp")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_generator}")
    file(READ "${_generator}" _source)
    set(_before [=[        tools_parser = p.trigger_rule("tool-calls", p.one_or_more(single_tool_parser + p.space()));]=])
    set(_after [=[        tools_parser = p.trigger_rule("tool-calls", inputs.parallel_tool_calls
            ? p.one_or_more(single_tool_parser + p.space())
            : single_tool_parser + p.space());]=])
    string(FIND "${_source}" "${_before}" _offset)
    if(_offset EQUAL -1)
        string(FIND "${_source}" "${_after}" _fixed_offset)
        if(_fixed_offset EQUAL -1)
            message(FATAL_ERROR "Unsupported llama.cpp JSON tool grammar: review the single-call patch for this revision")
        endif()
        return()
    endif()
    string(REPLACE "${_before}" "${_after}" _patched "${_source}")
    set(_output "${CMAKE_CURRENT_BINARY_DIR}/llama-patches/chat-auto-parser-generator.cpp")
    set(_existing "")
    if(EXISTS "${_output}")
        file(READ "${_output}" _existing)
    endif()
    if(NOT _existing STREQUAL _patched)
        file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/llama-patches")
        file(WRITE "${_output}" "${_patched}")
    endif()
    get_target_property(_sources llama-common SOURCES)
    set(_kept "")
    set(_replaced 0)
    foreach(_item IN LISTS _sources)
        get_filename_component(_name "${_item}" NAME)
        if(_name STREQUAL "chat-auto-parser-generator.cpp")
            math(EXPR _replaced "${_replaced}+1")
        else()
            list(APPEND _kept "${_item}")
        endif()
    endforeach()
    if(NOT _replaced EQUAL 1)
        message(FATAL_ERROR "Cannot identify the llama.cpp JSON tool grammar source uniquely")
    endif()
    set_property(TARGET llama-common PROPERTY SOURCES "${_kept}")
    target_sources(llama-common PRIVATE "${_output}")
endfunction()
