# Compile corrected native tool parsers without modifying an external checkout.
function(iilocal_compile_llama_common_copy _original _patched)
    get_filename_component(_name "${_original}" NAME)
    set(_output "${CMAKE_CURRENT_BINARY_DIR}/llama-patches/${_name}")
    set(_existing "")
    if(EXISTS "${_output}")
        file(READ "${_output}" _existing)
    endif()
    if(NOT _existing STREQUAL _patched)
        file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/llama-patches")
        file(WRITE "${_output}" "${_patched}")
    endif()
    get_target_property(_sources llama-common SOURCES)
    set(_kept "")
    set(_replaced 0)
    foreach(_item IN LISTS _sources)
        get_filename_component(_item_name "${_item}" NAME)
        if(_item_name STREQUAL _name)
            math(EXPR _replaced "${_replaced}+1")
        else()
            list(APPEND _kept "${_item}")
        endif()
    endforeach()
    if(NOT _replaced EQUAL 1)
        message(FATAL_ERROR "Cannot identify the llama.cpp ${_name} source uniquely")
    endif()
    set_property(TARGET llama-common PROPERTY SOURCES "${_kept}")
    target_sources(llama-common PRIVATE "${_output}")
endfunction()

function(iilocal_fix_llama_tool_grammars)
    get_target_property(_common_dir llama-common SOURCE_DIR)
    set(_generator "${_common_dir}/chat-auto-parser-generator.cpp")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_generator}")
    file(READ "${_generator}" _source)
    set(_before [=[        tools_parser = p.trigger_rule("tool-calls", p.one_or_more(single_tool_parser + p.space()));]=])
    set(_after [=[        tools_parser = p.trigger_rule("tool-calls", inputs.parallel_tool_calls
            ? p.one_or_more(single_tool_parser + p.space())
            : single_tool_parser + p.space());]=])
    string(FIND "${_source}" "${_before}" _offset)
    if(_offset EQUAL -1)
        string(FIND "${_source}" "${_after}" _fixed_offset)
        if(_fixed_offset EQUAL -1)
            message(FATAL_ERROR "Unsupported llama.cpp JSON tool grammar: review the single-call patch for this revision")
        endif()
    else()
        string(REPLACE "${_before}" "${_after}" _patched "${_source}")
        iilocal_compile_llama_common_copy("${_generator}" "${_patched}")
    endif()

    set(_chat "${_common_dir}/chat.cpp")
    set(_qwen_file "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/LlamaQwenTools.cpp.in")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_chat}" "${_qwen_file}")
    file(READ "${_chat}" _source)
    file(READ "${_qwen_file}" _qwen_file_contents)
    set(_signature "static common_chat_params common_chat_params_init_qwen3_coder(")
    string(FIND "${_source}" "${_signature}" _start)
    if(_start EQUAL -1)
        message(FATAL_ERROR "Cannot identify the native Qwen tool parser")
    endif()
    string(SUBSTRING "${_source}" ${_start} -1 _tail)
    string(FIND "${_tail}" "static common_chat_params common_chat_params_init_gpt_oss(" _end)
    if(_end EQUAL -1)
        message(FATAL_ERROR "Unsupported Qwen tool parser source layout")
    endif()
    string(SUBSTRING "${_tail}" 0 ${_end} _method)
    string(SHA256 _method_hash "${_method}")
    string(FIND "${_qwen_file_contents}" "${_signature}" _fixed_start)
    string(SUBSTRING "${_qwen_file_contents}" ${_fixed_start} -1 _fixed_method)
    if(_method_hash STREQUAL "a44c51fac0c56a9aed8f048ad7467f593540eff6fb912799760dca734cd4c1bd")
        string(REPLACE "${_method}" "${_qwen_file_contents}" _patched "${_source}")
        iilocal_compile_llama_common_copy("${_chat}" "${_patched}")
    elseif(NOT _method STREQUAL _fixed_method)
        message(FATAL_ERROR "Unsupported native Qwen tool parser revision: review the downstream correction")
    endif()
endfunction()
